[W 150529 15:10:19 web:1825] 405 GET /user/create (::1) 4.52ms
[I 150529 15:10:44 autoreload:195] ./server.py modified; restarting server
[I 150529 15:10:48 web:1825] 200 GET /user/create (::1) 1.06ms
[I 150529 15:11:10 autoreload:195] ./server.py modified; restarting server
[I 150529 15:11:12 web:1825] 200 GET /user/create (::1) 0.90ms
[I 150529 15:17:27 autoreload:195] ./server.py modified; restarting server
[I 150529 15:17:39 autoreload:195] ./server.py modified; restarting server
[I 150529 15:30:34 autoreload:195] ./server.py modified; restarting server
[I 150529 15:31:14 autoreload:195] ./server.py modified; restarting server
[I 150529 15:32:11 autoreload:195] ./server.py modified; restarting server
[I 150529 15:33:21 autoreload:195] ./server.py modified; restarting server
[I 150529 15:33:33 autoreload:195] ./server.py modified; restarting server
[I 150529 15:33:49 autoreload:195] ./server.py modified; restarting server
[I 150529 15:38:15 autoreload:195] ./server.py modified; restarting server
[I 150529 15:38:25 web:1825] 200 GET /user/create (::1) 1.72ms
[E 150529 15:40:38 web:1421] Uncaught exception POST /user/create (::1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/create', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '28', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 286, in post
        self.write(e)
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 655, in write
        raise TypeError("write() only accepts bytes, unicode, and dict objects")
    TypeError: write() only accepts bytes, unicode, and dict objects
[E 150529 15:40:38 web:1825] 500 POST /user/create (::1) 9.94ms
[I 150529 15:41:00 autoreload:195] ./server.py modified; restarting server
[I 150529 15:41:02 web:1825] 200 POST /user/create (::1) 2.38ms
[I 150529 15:43:29 autoreload:195] ./server.py modified; restarting server
[I 150529 15:43:35 web:1825] 200 POST /user/create (::1) 2.82ms
[I 150529 15:43:49 autoreload:195] ./server.py modified; restarting server
[I 150529 15:43:53 web:1825] 200 POST /user/create (127.0.0.1) 3.57ms
[I 150529 15:45:31 web:1825] 200 POST /user/create (127.0.0.1) 1.22ms
[I 150529 15:45:44 web:1825] 200 POST /user/create (127.0.0.1) 0.44ms
[I 150529 15:45:47 web:1825] 200 POST /user/create (127.0.0.1) 0.51ms
[I 150529 15:50:13 web:1825] 200 POST /user/create (127.0.0.1) 3.20ms
[I 150529 16:07:11 autoreload:195] ./server.py modified; restarting server
[E 150529 16:07:16 web:1421] Uncaught exception POST /user/create (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/create', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '28', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 288, in post
        cur.commit()
    AttributeError: 'sqlite3.Cursor' object has no attribute 'commit'
[E 150529 16:07:16 web:1825] 500 POST /user/create (127.0.0.1) 10.84ms
[I 150529 16:07:30 autoreload:195] ./server.py modified; restarting server
[I 150529 16:07:31 web:1825] 200 POST /user/create (127.0.0.1) 5.07ms
[I 150529 16:08:02 web:1825] 200 POST /user/create (127.0.0.1) 0.84ms
[I 150529 16:10:08 autoreload:195] ./server.py modified; restarting server
[I 150529 16:10:34 autoreload:195] ./server.py modified; restarting server
[I 150529 16:10:37 web:1825] 200 POST /user/create (127.0.0.1) 3.10ms
[I 150529 16:13:06 autoreload:195] ./server.py modified; restarting server
[I 150529 16:13:08 web:1825] 200 POST /user/create (127.0.0.1) 6.16ms
[I 150529 16:24:04 autoreload:195] ./server.py modified; restarting server
[I 150529 16:29:55 web:1825] 200 POST /user/create (127.0.0.1) 2.95ms
[E 150529 16:30:02 web:1421] Uncaught exception POST /user/create (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/create', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '29', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 292, in post
        self.resp(200, "User created",{"token": token})
    TypeError: resp() takes at most 3 arguments (4 given)
[E 150529 16:30:02 web:1825] 500 POST /user/create (127.0.0.1) 4.98ms
[I 150529 16:31:53 autoreload:195] ./server.py modified; restarting server
[I 150529 16:32:04 web:1825] 200 POST /user/create (127.0.0.1) 4.77ms
[E 150529 16:32:12 web:1421] Uncaught exception POST /user/create (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/create', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '29', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 292, in post
        self.resp(200, msg = "User created",dict = {"token": token})
    TypeError: resp() got multiple values for keyword argument 'msg'
[E 150529 16:32:12 web:1825] 500 POST /user/create (127.0.0.1) 4.68ms
[I 150529 16:33:26 autoreload:195] ./server.py modified; restarting server
[I 150529 16:33:34 web:1825] 200 POST /user/create (127.0.0.1) 2.05ms
[E 150529 16:33:42 web:1421] Uncaught exception POST /user/create (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/create', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '29', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 292, in post
        self.resp(200, msg = "User created",dict = {"token": token})
      File "./server.py", line 194, in resp
        response += dict
    TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'
[E 150529 16:33:42 web:1825] 500 POST /user/create (127.0.0.1) 4.86ms
[I 150529 16:34:11 autoreload:195] ./server.py modified; restarting server
[I 150529 16:39:50 autoreload:195] ./server.py modified; restarting server
[I 150529 16:40:12 web:1825] 200 POST /user/create (127.0.0.1) 4.48ms
[E 150529 16:40:20 web:1421] Uncaught exception POST /user/create (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/create', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '29', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 292, in post
        self.resp(200, msg = "User created",dict = {"token": token})
      File "./server.py", line 194, in resp
        response = dict(response, **dict);
    TypeError: 'dict' object is not callable
[E 150529 16:40:20 web:1825] 500 POST /user/create (127.0.0.1) 5.62ms
[I 150529 16:41:05 autoreload:195] ./server.py modified; restarting server
[I 150529 16:41:17 autoreload:195] ./server.py modified; restarting server
[E 150529 16:41:18 web:1421] Uncaught exception POST /user/create (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/create', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '29', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 265, in post
        self.resp(200, msg = "User created",dict = {"token": token})
    UnboundLocalError: local variable 'token' referenced before assignment
[E 150529 16:41:18 web:1825] 500 POST /user/create (127.0.0.1) 6.79ms
[I 150529 16:41:33 autoreload:195] ./server.py modified; restarting server
[E 150529 16:41:34 web:1421] Uncaught exception POST /user/create (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/create', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '29', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 279, in post
        self.resp(200, msg = "User created",dict = {"token": token})
    TypeError: resp() got an unexpected keyword argument 'dict'
[E 150529 16:41:34 web:1825] 500 POST /user/create (127.0.0.1) 3.19ms
[I 150529 16:41:46 autoreload:195] ./server.py modified; restarting server
[I 150529 16:41:47 web:1825] 200 POST /user/create (127.0.0.1) 2.05ms
[I 150529 16:42:08 autoreload:195] ./server.py modified; restarting server
[I 150529 16:42:08 web:1825] 200 POST /user/create (127.0.0.1) 1.99ms
[I 150529 16:42:20 autoreload:195] ./server.py modified; restarting server
[I 150529 16:45:31 autoreload:195] ./server.py modified; restarting server
[I 150529 16:45:40 web:1825] 200 POST /user/create (127.0.0.1) 2.51ms
[I 150529 16:46:39 autoreload:195] ./server.py modified; restarting server
[I 150529 16:47:50 autoreload:195] ./server.py modified; restarting server
[I 150529 17:03:52 web:1825] 302 GET /user/me (127.0.0.1) 2.18ms
[I 150529 17:04:34 autoreload:195] ./server.py modified; restarting server
[I 150529 17:04:38 web:1825] 302 GET /user/me (127.0.0.1) 1.34ms
[I 150529 17:13:32 autoreload:195] ./server.py modified; restarting server
[I 150529 17:13:46 web:1825] 200 GET /user/login (127.0.0.1) 2.55ms
[W 150529 17:13:59 web:1825] 404 GET /user/me (127.0.0.1) 2.59ms
[I 150529 17:14:26 web:1825] 200 POST /user/login (127.0.0.1) 6.52ms
[I 150529 17:14:41 web:1825] 200 POST /user/login (127.0.0.1) 0.92ms
[I 150529 17:15:33 autoreload:195] ./server.py modified; restarting server
[I 150529 17:15:41 autoreload:195] ./server.py modified; restarting server
[I 150529 17:20:41 autoreload:195] ./server.py modified; restarting server
[I 150529 17:20:55 web:1825] 302 GET / (127.0.0.1) 2.03ms
[I 150529 17:21:40 web:1825] 302 GET / (::1) 0.58ms
[I 150529 17:21:40 web:1825] 200 GET /user/login?next=%2F (::1) 0.46ms
[W 150529 17:21:41 web:1825] 404 GET /favicon.ico (::1) 3.74ms
[I 150529 17:32:38 web:1825] 200 GET /?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBhYWEuY29tIn0.xNCfZ6zR1Z7qLIswGzMFPOREpJw30_ohEZW4BVIJ7MY (::1) 0.93ms
[I 150529 17:35:35 autoreload:195] ./server.py modified; restarting server
[I 150529 17:38:39 web:1825] 302 GET / (::1) 3.14ms
[I 150529 17:40:19 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 17:45:36 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 17:45:56 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 17:47:50 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 17:51:36 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 17:53:58 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 17:54:58 web:1825] 200 POST /user/login (::1) 5.46ms
[I 150529 17:55:10 web:1825] 200 POST /user/login (::1) 0.86ms
[I 150529 17:55:30 web:1825] 200 POST /user/login (::1) 0.62ms
[I 150529 17:55:33 web:1825] 200 POST /user/login (::1) 0.60ms
[I 150529 17:56:00 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 17:56:12 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 17:56:37 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 18:02:35 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[W 150529 18:04:46 web:1825] 404 POST /changepassword (::1) 7.52ms
[W 150529 18:05:03 web:1825] 403 POST /user/changepassword (::1) 0.79ms
[E 150529 18:06:40 web:1421] Uncaught exception POST /user/changepassword (::1)
    HTTPServerRequest(protocol='http', host='localhost:8080', method='POST', uri='/user/changepassword', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8080', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '129', 'Accept': '*/*', 'User-Agent': 'curl/7.37.1'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 2626, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py", line 194, in post
        logging.info("%s want to change password with token %s"%(email,token))
    NameError: global name 'logging' is not defined
[E 150529 18:06:40 web:1825] 500 POST /user/changepassword (::1) 3.22ms
[I 150529 18:10:24 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 18:10:57 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 18:11:01 handlers:195] aaa@aaa.com want to change password with token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBhYWEuY29tIn0.xNCfZ6zR1Z7qLIswGzMFPOREpJw30_ohEZW4BVIJ7MY
[I 150529 18:11:01 web:1825] 200 POST /user/changepassword (127.0.0.1) 7.99ms
[I 150529 18:16:21 web:1825] 302 GET / (127.0.0.1) 0.69ms
[I 150529 18:16:33 web:1825] 302 GET / (::1) 0.44ms
[I 150529 18:17:07 web:1825] 302 GET / (::1) 0.48ms
[I 150529 18:17:10 web:1825] 302 GET / (::1) 0.40ms
[I 150529 18:20:06 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 18:20:09 web:1825] 302 GET / (::1) 2.31ms
[I 150529 18:20:29 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 18:20:30 web:1825] 302 GET / (::1) 1.52ms
[I 150529 18:20:43 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 18:20:45 web:1825] 302 GET / (::1) 1.28ms
[I 150529 18:21:08 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 18:21:09 web:1825] 302 GET / (::1) 1.55ms
[I 150529 18:22:00 web:1825] 200 GET / (::1) 0.83ms
[I 150529 18:22:24 autoreload:195] /Users/Jack/Documents/Workspace/slickedit/esp8266_iot_node/handlers.py modified; restarting server
[I 150529 18:23:26 handlers:195] aaa@aaa.com want to change password with token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjIiLCJlbWFpbCI6ImFhYUBhYWEuY29tIn0.jsQ4jVaa8wuS1JA5moS-klV6TUyvz0VETnEZqec6TYM
[I 150529 18:23:26 web:1825] 200 POST /user/changepassword (::1) 4.91ms
